# Generated by Django 4.2.7 on 2024-02-10 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreactions',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.postsfeed'),
        ),
        migrations.AlterField(
            model_name='postreactions',
            name='reactions',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='postreactions',
            unique_together={('user', 'post')},
        ),
    ]
