from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path('api/token/', views.CustomTokenObtainPairView.as_view(), name='token_obtain'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/register/', views.RegisterUser.as_view(), name='register_user'),
    path('api/username/<int:id>', views.ShowUsernameView.as_view(), name='username'),
    path('api/weight/', views.WeightListView.as_view(), name='user_weight'),
    path('api/weight/show/<int:user_id>', views.ViewWeightList.as_view(), name='show_user_weight'),
    path('api/weight/<int:user_id>', views.UpdateWeightListView.as_view(), name='user_weight'),
    path('api/weight/past/<int:user_id>', views.ViewPastWeightListView.as_view(), name='past_user_weight'),
    path('api/goals/', views.SetGoalsView.as_view(), name='user_goals'),
    path('api/goals/<int:user_id>', views.ShowGoalsView.as_view(), name='show_user_goals'),
    path('api/goals/remove/<int:id>', views.RemoveGoalsView.as_view(), name='remove_user_goals'),    
    path('api/exercise/', views.ViewExerciseListView.as_view(), name='exercise'),
    path('api/workout/', views.WorkoutListView.as_view(), name='workout'),
    path('api/workout/<int:user_id>', views.ViewWorkoutListView.as_view(), name='user_workout'),
    path('api/workout/details/<int:workout_id>', views.ViewWorkoutDetailsView.as_view(), name='user_workout_details'),
    path('api/workout/add/', views.AddWorkoutDetailsView.as_view(), name='add_workout'),
    path('api/workout/exercise/<int:user_id>/<int:exercise_id>', views.ViewExerciseDetailsView.as_view(), name='user_exercise'),
    path('api/workout/compound/<int:user_id>/<int:exercise_id>', views.ViewCompoundDetailsView.as_view(), name='user_compound'),
    path('api/workout/exercise/<int:user_id>', views.ViewAllWorkoutsDetailsView.as_view(), name='user_all_exercise'),
    path('api/workout/remove/<int:workout_ID>', views.RemoveWorkoutView.as_view(), name='remove_workout'),
    path('api/set/remove/<int:set_id>', views.RemoveSetView.as_view(), name='remove_set'),
    path('api/set/update/<int:set_id>', views.UpdateSetView.as_view(), name='update_set'),
    path('api/set/<int:set_id>', views.ViewSetDetailsView.as_view(), name='view_set'),
    path('api/friend/create', views.SendRequestView.as_view(), name='friend_create'),
    path('api/friend/requests/<int:friendship_receiver_id>', views.SeeFriendRequestView.as_view(), name='received_request'),
    path('api/friend/decision/<int:id>', views.ReplyRequestView.as_view(), name='reply_request'),
    path('api/friend/remove/<int:id>', views.RejectFriendView.as_view(), name='reject_friend'),
    path('api/friend/view/<int:id>', views.ViewFriends.as_view(), name='friends_view'),
    path('api/message/send', views.SendMessageView.as_view(), name='send_message'),
    path('api/message/view/<int:sender_id>/<int:receiver_id>', views.ViewMessageView.as_view(), name='view_message'),
    path('api/post/create', views.SendPostsView.as_view(), name='post_create'),
    path('api/post/showall', views.ShowAllPostsView.as_view(), name='show_all_posts'),
    path('api/post/show/<int:user_id>', views.ShowUserPostView.as_view(), name='show_user_post'),
    path('api/post/friends/<int:id>', views.ShowFriendsPostsView.as_view(), name='show_friends_post'),
    path('api/post/remove/<int:id>', views.RemovePostView.as_view(), name='remove_post'),
    path('api/comment/create', views.ReplyCommentView.as_view(), name='reply_comment'),
    path('api/comment/show/<int:post_id>', views.ViewPostCommentsView.as_view(), name='show_comments'),
    path('api/post/reactions/Like/<int:post_id>', views.ViewUserPostLikeReactions.as_view(), name='like_reactions'),
    path('api/post/reactions/Goodf/<int:post_id>', views.ViewUserPostGoodfReactions.as_view(), name='good_reactions'),
    path('api/post/reactions/Badf/<int:post_id>', views.ViewUserPostBadfReactions.as_view(), name='bad_reactions'),
    path('api/post/reactions/Strong/<int:post_id>', views.ViewUserPostStrongReactions.as_view(), name='strong_reactions'),
    path('api/post/reactions/GoodW/<int:post_id>', views.ViewUserPostGoodWeightReactions.as_view(), name='goodW_reactions'),
    path('api/post/reactions/update/<int:id>', views.UpdatePostReactionsView.as_view(), name='update_reactions'),
    path('api/post/reactions/view/<int:user_id>/<int:post_id>', views.ViewUserReactionView.as_view(), name='view_reactions'),
]